#########################################################
#                 UHC -  Version 2.0                    #
#               Développeur : B. Goodes                 #
#########################################################

default-language-key: fr
