#########################################################
#                 UHC -  Version 1.0                    #
#               Développeur : B. Goodes                 #
#########################################################

default-language-code: fr

lobby:
  spawn-location:
    world-name: world
    x: 0
    y: 100
    z: 0
  default-gamemode: "ADVENTURE"