#########################################################
#                 UHC -  Version 1.0                    #
#               Développeur : B. Goodes                 #
#########################################################

default-language-key: fr
