#########################################################
#                 UHC -  Version 1.0                    #
#               Développeur : B. Goodes                 #
#########################################################

default-language-code: fr

lobby-settings:
  spawn-location: "world;0;100;0"
  default-gamemode: "ADVENTURE"